# Generated by Django 3.1.4 on 2020-12-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20201211_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='brief',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
