# Generated by Django 3.1.4 on 2020-12-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='brief',
            field=models.CharField(max_length=140),
        ),
    ]
