# Generated by Django 3.1.4 on 2020-12-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_tag_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created']},
        ),
    ]
