# Generated by Django 3.1.4 on 2020-12-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20201214_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pk']},
        ),
    ]
