# Generated by Django 3.1.4 on 2020-12-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20201214_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='brief',
            field=models.CharField(max_length=250),
        ),
    ]
