# Generated by Django 3.1.4 on 2021-01-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20210107_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
